theme = ['github.com/jpanther/lynx']
title = "The Random Episode"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
name = "The Random Episode Podcast"
headline = "Join long time friends and TV show enthusiasts, Varun and Christie, as they watch and recap a random episode, from a random season, from a television series they've NEVER seen before."
image = "logo.png"
links = [
    { instagram = "https://www.instagram.com/therandomepisodepod/" },
    { spotify = "https://open.spotify.com/show/7q23GgsGqmgLBX1W3fNL5y" },
    { youtube = "https://www.youtube.com/@TheRandomEpisode" },
    { apple = "https://podcasts.apple.com/us/podcast/the-random-episode/id1765733187" },
    { amazon = "https://music.amazon.com/podcasts/aa9bf956-0043-4895-9ef8-0cc9aef1ac46/the-random-episode" },
]

[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
